<?php
/**
 * zzv.cn
 * data for test
 * 2017.4 zhengzhou
 */
$ftype=$_GET["ftype"];
if($ftype==1)
    echo '[{"fbill":"12246","fqty":"102798","fbill_today":"201","fqty_today":"1428","fqty_out":"0"}]'
        .'###[{"fid":"1","fname":"济源","fbill":"63","fqty":"4","fbill_today":"","fqty_today":""},{"fid":"2","fname":"鹤壁","fbill":"77","fqty":"5","fbill_today":"","fqty_today":""},{"fid":"3","fname":"安阳","fbill":"227","fqty":"3","fbill_today":"","fqty_today":""},{"fid":"4","fname":"三门峡","fbill":"203","fqty":"9","fbill_today":"","fqty_today":""},{"fid":"5","fname":"信阳","fbill":"658","fqty":"5","fbill_today":"","fqty_today":""},{"fid":"6","fname":"焦作","fbill":"572","fqty":"29","fbill_today":"","fqty_today":""},{"fid":"7","fname":"开封","fbill":"559","fqty":"12","fbill_today":"","fqty_today":""},{"fid":"8","fname":"漯河","fbill":"511","fqty":"24","fbill_today":"","fqty_today":""},{"fid":"9","fname":"许昌","fbill":"596","fqty":"27","fbill_today":"","fqty_today":""},{"fid":"10","fname":"平顶山","fbill":"707","fqty":"21","fbill_today":"","fqty_today":""},{"fid":"11","fname":"濮阳","fbill":"670","fqty":"65","fbill_today":"","fqty_today":""},{"fid":"12","fname":"新乡","fbill":"926","fqty":"34","fbill_today":"","fqty_today":""},{"fid":"13","fname":"商丘","fbill":"639","fqty":"35","fbill_today":"","fqty_today":""},{"fid":"14","fname":"周口","fbill":"806","fqty":"39","fbill_today":"","fqty_today":""},{"fid":"15","fname":"驻马店","fbill":"1029","fqty":"44","fbill_today":"","fqty_today":""},{"fid":"16","fname":"洛阳","fbill":"1063","fqty":"19","fbill_today":"","fqty_today":""},{"fid":"17","fname":"南阳","fbill":"1225","fqty":"55","fbill_today":"","fqty_today":""},{"fid":"18","fname":"郑州","fbill":"1715","fqty":"19","fbill_today":"","fqty_today":""}]'
        .'###[{"fid":"1","fname":"Company A","fbill":"2912","fqty":"21784","fbill_today":"","fqty_today":""},{"fid":"2","fname":"Company B","fbill":"1053","fqty":"12801","fbill_today":"","fqty_today":""},{"fid":"3","fname":"Company C","fbill":"820","fqty":"9734","fbill_today":"","fqty_today":""},{"fid":"4","fname":"Company D","fbill":"607","fqty":"8235","fbill_today":"","fqty_today":""},{"fid":"5","fname":"Company E","fbill":"906","fqty":"7252","fbill_today":"","fqty_today":""},{"fid":"6","fname":"Company F","fbill":"855","fqty":"5259","fbill_today":"","fqty_today":""},{"fid":"7","fname":"Company G","fbill":"820","fqty":"5116","fbill_today":"","fqty_today":""},{"fid":"8","fname":"Company H","fbill":"539","fqty":"4614","fbill_today":"","fqty_today":""},{"fid":"9","fname":"Company I","fbill":"1212","fqty":"4365","fbill_today":"","fqty_today":""},{"fid":"10","fname":"Company J","fbill":"289","fqty":"4061","fbill_today":"","fqty_today":""},{"fid":"11","fname":"Company K","fbill":"848","fqty":"3691","fbill_today":"","fqty_today":""},{"fid":"12","fname":"Company L","fbill":"98","fqty":"1935","fbill_today":"","fqty_today":""},{"fid":"13","fname":"Company M","fbill":"250","fqty":"1922","fbill_today":"","fqty_today":""},{"fid":"14","fname":"Company N","fbill":"111","fqty":"1787","fbill_today":"","fqty_today":""},{"fid":"15","fname":"Company O","fbill":"183","fqty":"1677","fbill_today":"","fqty_today":""},{"fid":"16","fname":"Company P","fbill":"61","fqty":"1540","fbill_today":"","fqty_today":""}]'
        .'###[{"fid":"1","fname":"Product A","fbill":"249","fqty":"2975","fbill_today":"","fqty_today":""},{"fid":"2","fname":"Product B","fbill":"811","fqty":"3132","fbill_today":"","fqty_today":""},{"fid":"3","fname":"Product C","fbill":"378","fqty":"3215","fbill_today":"","fqty_today":""},{"fid":"4","fname":"Product D","fbill":"551","fqty":"3675","fbill_today":"","fqty_today":""},{"fid":"5","fname":"Product E","fbill":"1056","fqty":"3681","fbill_today":"","fqty_today":""},{"fid":"6","fname":"Product F","fbill":"561","fqty":"5273","fbill_today":"","fqty_today":""},{"fid":"7","fname":"Product G","fbill":"369","fqty":"6596","fbill_today":"","fqty_today":""},{"fid":"8","fname":"Product H","fbill":"344","fqty":"6677","fbill_today":"","fqty_today":""}]'
        .'###[{"fid":"1","fname":"Prouct AA","fbill":"10","fqty":"61","fbill_today":"","fqty_today":""},{"fid":"2","fname":"Prouct BB","fbill":"13","fqty":"73","fbill_today":"","fqty_today":""},{"fid":"3","fname":"Prouct CC","fbill":"10","fqty":"91","fbill_today":"","fqty_today":""},{"fid":"4","fname":"Prouct DD","fbill":"25","fqty":"92","fbill_today":"","fqty_today":""},{"fid":"5","fname":"Prouct EE","fbill":"6","fqty":"93","fbill_today":"","fqty_today":""},{"fid":"6","fname":"Prouct FF","fbill":"2","fqty":"100","fbill_today":"","fqty_today":""},{"fid":"7","fname":"Prouct HH","fbill":"14","fqty":"172","fbill_today":"","fqty_today":""},{"fid":"8","fname":"Prouct II","fbill":"11","fqty":"206","fbill_today":"","fqty_today":""}]';
else
    echo '[{"platform":"[total]","qtyall":"5669","rate":"0"},{"platform":"CompanyA","qtyall":"2355","rate":"0"},{"platform":"CompanyB","qtyall":"1831","rate":"0"},{"platform":"CompanyC","qtyall":"263","rate":"0"},{"platform":"CompanyD","qtyall":"227","rate":"0"},{"platform":"CompanyE","qtyall":"227","rate":"0"},{"platform":"CompanyF","qtyall":"162","rate":"0"},{"platform":"CompanyG","qtyall":"124","rate":"0"},{"platform":"CompanyH","qtyall":"118","rate":"0"},{"platform":"CompanyI","qtyall":"78","rate":"0"},{"platform":"CompanyJ","qtyall":"66","rate":"0"},{"platform":"CompanyK","qtyall":"47","rate":"0"},{"platform":"CompanyL","qtyall":"43","rate":"0"},{"platform":"CompanyM","qtyall":"40","rate":"0"},{"platform":"CompanyN","qtyall":"38","rate":"0"},{"platform":"CompanyO","qtyall":"26","rate":"0"},{"platform":"CompanyP","qtyall":"13","rate":"0"},{"platform":"CompanyQ","qtyall":"10","rate":"0"},{"platform":"CompanyR","qtyall":"1","rate":"0"}]';
?>